// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "intro",


    {
      type: "category",
      label: "Labs",
      items: [
        {
          type: "autogenerated",
          dirName: "labs",
        },
      ],
    },






  ],
};

module.exports = sidebars;